---
<<<<<<< HEAD
GEOSERVER_URL: "http://build.geonode.org/geoserver/latest/geoserver-2.12.2.war"
DATA_DIR_URL: "http://build.geonode.org/geoserver/latest/data-2.12.2.zip"
=======
GEOSERVER_URL: "https://build.geo-solutions.it/geonode/geoserver/latest/geoserver-2.13.x.war"
DATA_DIR_URL: "https://build.geo-solutions.it/geonode/geoserver/latest/data-2.13.x.zip"
>>>>>>> 7b5b7777f29edd637f30c2c1b7ea44a812e45bad
JETTY_RUNNER_URL: "http://repo2.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.4.7.v20170914/jetty-runner-9.4.7.v20170914.jar"
WINDOWS:
  py2exe: "http://downloads.sourceforge.net/project/py2exe/py2exe/0.6.9/py2exe-0.6.9.win32-py2.7.exe"
  nose: "https://s3.amazonaws.com/geonodedeps/nose-1.3.3.win32-py2.7.exe"
  pyproj: "https://pyproj.googlecode.com/files/pyproj-1.9.3.win32-py2.7.exe"
  lxml: "https://pypi.python.org/packages/2.7/l/lxml/lxml-3.6.0.win32-py2.7.exe"
<<<<<<< HEAD
MIGRATE_APPS:
  - account
  - contenttypes
  - sites
  - auth
  - people
  - base
  - services
  - oauth2_provider
=======
>>>>>>> 7b5b7777f29edd637f30c2c1b7ea44a812e45bad
