version: '2'
services:
  django:
    environment:
      DEBUG: 'True'
      GEONODE_LB_HOST_IP: localhost
      GEONODE_LB_PORT: 80
      SITEURL: https://iws.ismar.cnr.it/
      ALLOWED_HOSTS: "['localhost', 'iws.ismar.cnr.it', 'www.seastorms.eu', ']"
      GEOSERVER_PUBLIC_LOCATION: https://iws.ismar.cnr.it/geoserver/

  celery:
    environment:
      DEBUG: 'True'
      GEONODE_LB_HOST_IP: localhost
      GEONODE_LB_PORT: 80
      SITEURL: https://iws.ismar.cnr.it/
      ALLOWED_HOSTS: "['localhost', 'iws.ismar.cnr.it', 'www.seastorms.eu']"
      GEOSERVER_PUBLIC_LOCATION: https://iws.ismar.cnr.it/geoserver/

  geoserver:
    environment:
      GEONODE_LB_HOST_IP: django
      GEONODE_LB_PORT: 80
      NGINX_BASE_URL: iws.ismar.cnr.it

