version: '2'
services:
  django:
    environment:
      DEBUG: 'True'
      GEONODE_LB_HOST_IP: localhost
      GEONODE_LB_PORT: 80
      SITEURL: https://iws.seastorms.eu/
      ALLOWED_HOSTS: "['localhost', 'iws.seastorms.eu', 'www.seastorms.eu']"
      GEOSERVER_PUBLIC_LOCATION: https://iws.seastorms.eu/geoserver/

  celery:
    environment:
      DEBUG: 'True'
      GEONODE_LB_HOST_IP: localhost
      GEONODE_LB_PORT: 80
      SITEURL: https://iws.seastorms.eu/
      ALLOWED_HOSTS: "['localhost', 'iws.seastorms.eu', 'www.seastorms.eu']"
      GEOSERVER_PUBLIC_LOCATION: https://iws.seastorms.eu/geoserver/

  geoserver:
    environment:
      GEONODE_LB_HOST_IP: django
      GEONODE_LB_PORT: 80
      NGINX_BASE_URL: iws.seastorms.eu

