version: '2.2'
services:
  django:
  #    command: python manage.py runserver --settings=iws.settings 0.0.0.0:8000
    ports:
    - 8000:8000
    expose:
    - 8000
    env_file:
    - ./.env
    environment:
#      DEBUG: 'True'
      GEONODE_LB_HOST_IP: localhost
      GEONODE_LB_PORT: 80
      SITEURL: ${SITE_URL}
      ALLOWED_HOSTS: "['localhost','*', 'django', 'django:8000']"
      GEOSERVER_PUBLIC_LOCATION: http://localhost/gs/

  celery:
    environment:
      DEBUG: 'True'
      GEONODE_LB_HOST_IP: localhost
      GEONODE_LB_PORT: 80
      SITEURL: http://localhost/
      ALLOWED_HOSTS: "['localhost']"
      GEOSERVER_PUBLIC_LOCATION: http://localhost/gs/

  geoserver:
    environment:
      GEONODE_LB_HOST_IP: localhost
      GEONODE_LB_PORT: 80
      NGINX_BASE_URL:

#  tds:
#    image: unidata/thredds-docker:4.6.12
#    ports:
#      - "82:8080"
#      - "445:8443"
#      - "8445:8443"
#    container_name: tds4${COMPOSE_PROJECT_NAME}
#
#    volumes:
#      - ./volumes/tds/tomcat/logs/:/usr/local/tomcat/logs/
#      - ./volumes/tds/thredds/logs/:/usr/local/tomcat/content/thredds/logs/
#      #- /path/to/your/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
#      - ./volumes/tds/thredds/directory:/usr/local/tomcat/content/thredds
#      #- /usr3/tds/data/:/usr/local/tomcat/content/data
#      - ./volumes/tds/tomcat/conf:/usr/local/tomcat/conf/
#      #- ./volumes/tds/data/directory1:/path/to/your/data/directory2
#    env_file:
#      - ./.env