VERSION 0.6

django:
    ARG EARTHLY_GIT_HASH
    ARG EARTHLY_TARGET_NAME
    ARG BRANCH
    ARG USER
    FROM DOCKERFILE .
    SAVE IMAGE --push ghcr.io/$USER/iws/iws_$EARTHLY_TARGET_NAME:$EARTHLY_GIT_HASH
    SAVE IMAGE --push ghcr.io/$USER/iws/iws_$EARTHLY_TARGET_NAME:$BRANCH
