export default {
  "sea_level": "Sea Level",
  "wsh": "Wave Height",
  "wmp": "Wave Period",
  "wmd": "Wave Direction",

  lines: {
  "sea_level-min": "Sea Level min",
  "wsh-min": "Wave Height min",
  "wmp-min": "Wave Period min",
  "wmd-min": "Wave Direction min",
  "sea_level-area": "Sea Level std",
  "wsh-area": "Wave Height std",
  "wmp-area": "Wave Period std",
  "wmd-area": "Wave Direction std",
  "sea_level-max": "Sea Level max",
  "wsh-max": "Wave Height max",
  "wmp-max": "Wave Period max",
  "wmd-max": "Wave Direction max",
  "sea_level-mean": "Sea Level mean",
  "wsh-mean": "Wave Height mean",
  "wmp-mean": "Wave Period mean",
  "wmd-mean": "Wave Direction mean",
  "sea_level-station": "Sea Level station",
  "wmp-station": "Wave Period station",
  "wmd-station": "Wave Direction station",
  "wsh-station": "Wave Height station",
  },

  crosshair: {
  "sea_level-area": "Sea Level forecast std",
  "wsh-area": "Wave Height forecast std",
  "wmp-area": "Wave Period forecast std",
  "wmd-area": "Wave Direction forecast std",
  "sea_level-max": "Sea Level max",
  "wsh-max": "Wave Height max",
  "wmp-max": "Wave Period max",
  "wmd-max": "Wave Direction max",
  "sea_level-mean": "Sea Level forecast mean",
  "wsh-mean": "Wave Height forecast mean",
  "wmp-mean": "Wave Period forecast mean",
  "wmd-mean": "Wave Direction forecast mean",
  "sea_level-station": "Sea Level station measure",
  "wmp-station": "Wave Period station measure",
  "wmd-station": "Wave Direction station measure",
  "wsh-station": "Wave Height station measure",
  },

  "um": {
  "sea_level": "cm",
  "wsh": "m",
  "wmp": "s",
  "wmd": "°",
  }
}
