
FROM nginx
MAINTAINER GeoNode development team Amefad

COPY le_fullchain.pem /etc/ssl/certs/le_fullchain.pem
COPY le_privkey.pem /etc/ssl/private/le_privkey.pem

COPY nginx.conf /etc/nginx/nginx.conf
