# Generated by Django 3.2.15 on 2022-09-19 15:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sea_storm_atlas', '0015_auto_20190630_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coastalsegment',
            options={'ordering': ['code', 'partition']},
        ),
        migrations.AlterField(
            model_name='stormevent',
            name='coastalsegment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sea_storm_atlas.coastalsegment', verbose_name='Coastal segment'),
        ),
        migrations.AlterField(
            model_name='stormevent',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Insert a reference point related to the sea storm events', null=True, srid=3035, verbose_name='Event location'),
        ),
    ]
