# Generated by Django 3.2.16 on 2022-11-23 12:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sea_storm_atlas', '0016_auto_20220919_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('eu_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StormEventEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('area_code', models.CharField(blank=True, max_length=5, null=True)),
                ('area_partition', models.CharField(blank=True, max_length=2, null=True)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('is_aggregated', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('coastalsegment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sea_storm_atlas.coastalsegment', verbose_name='Coastal segment')),
                ('origins', models.ManyToManyField(blank=True, to='sea_storm_atlas.Origin')),
            ],
        ),
        migrations.CreateModel(
            name='StormEventEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Insert a reference point related to the sea storm events', null=True, srid=3035, verbose_name='Event location')),
                ('damage', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('damage_categories', models.ManyToManyField(blank=True, to='sea_storm_atlas.DamageCategory')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='effects', to='sea_storm_atlas.stormevententry')),
            ],
        ),
    ]
