# Generated by Django 3.2.16 on 2022-11-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea_storm_atlas', '0017_damagecategory_origin_stormeventeffect_stormevententry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stormevententry',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
