# Generated by Django 3.2.16 on 2022-11-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea_storm_atlas', '0020_auto_20221124_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='StormEventEffectComplete',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
