# Generated by Django 3.2.16 on 2022-11-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sea_storm_atlas', '0021_stormeventeffectcomplete'),
    ]

    operations = [
        migrations.RunSQL('''
            create or replace view sea_storm_atlas_effect_complete as
                select 
                    eff.id,
                    eff.date,
                    eff.description,
                    eff.geom,
                    eff.damage,
                    eff.flooding_level,
                    ev.id as event_id,
                    ev.date_start as event_start_date,
                    ev.date_end as event_end_date,
                    ev.description as event_description,
                    ev.coastalsegment_id as coastalsegment_id,
                    ev.is_aggregated as event_is_aggregated
                from sea_storm_atlas_stormeventeffect eff
                join sea_storm_atlas_stormevententry ev on eff.event_id = ev.id
        ''', 'drop view sea_storm_atlas_effect_complete')
    ]
