# Generated by Django 3.2.16 on 2022-11-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sea_storm_atlas', '0023_auto_20221129_0828'),
    ]

    operations = [
        migrations.RunSQL('''
            create or replace view sea_storm_atlas_effect_complete as
                select eff.id,
                    eff.date,
                    eff.description,
                    eff.geom,
                    eff.damage,
                    eff.flooding_level,
                    ev.id as event_id,
                    ev.date_start as event_start_date,
                    ev.date_end as event_end_date,
                    ev.description as event_description,
                    ev.coastalsegment_id as coastalsegment_id,
                    ev.is_aggregated as event_is_aggregated,
                    ssac.subregion as coastalsegment_subregion,
                    string_agg(ssad.name, ', ') as damage_types,
                    string_agg(ssao.name, ', ') as origins,
                    count(dd.id) as documents
                from sea_storm_atlas_stormeventeffect eff
                join sea_storm_atlas_stormevententry ev on eff.event_id = ev.id
                left join sea_storm_atlas_stormeventeffect_damage_categories ssasdc on ssasdc.stormeventeffect_id = eff.id
                left join sea_storm_atlas_damagecategory ssad on ssasdc.damagecategory_id = ssad.id
                left join sea_storm_atlas_stormevententry_origins ssaso on ssaso.stormevententry_id = ev.id
                left join sea_storm_atlas_origin ssao on ssao.id  = ssaso.origin_id
                join sea_storm_atlas_coastalsegment ssac on ev.coastalsegment_id = ssac.id
                left join documents_documentresourcelink dd on dd.object_id = eff.id
                group by eff.id, ev.id, ssac.subregion 
        ''', '')
    ]
