# Generated by Django 3.2.15 on 2022-09-19 15:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('location_label', models.TextField(editable=False)),
                ('station_code', models.TextField(editable=False)),
                ('station_label', models.TextField(editable=False)),
                ('code', models.TextField(editable=False)),
                ('parameter_id', models.IntegerField(editable=False)),
                ('geo', django.contrib.gis.db.models.fields.PointField(editable=False, srid=4326)),
            ],
            options={
                'db_table': 'measurements_station_geo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationData',
            fields=[
                ('timestamp', models.DateTimeField(editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField(editable=False)),
                ('value_norm', models.FloatField(editable=False)),
                ('location', models.TextField(editable=False)),
                ('location_id', models.IntegerField(editable=False)),
                ('parameter', models.TextField(editable=False)),
                ('parameter_id', models.IntegerField(editable=False)),
                ('network', models.TextField(editable=False)),
            ],
            options={
                'db_table': 'measurements_grafana_view',
                'managed': False,
            },
        ),
    ]
